### ISSUE TITLE
can't get tierpsy tracker to work on mac or pc, possibly can't get good install?

### ISSUE THREAD

**Issue by ohaganr** [Tierpsy/tierpsy-tracker#49]
Hi Folks,
We would love to be able to use (and cite!!) your tool tierpsy tracker to analyze locomotion defects in our C. elegans mutants, but can't seem to get in to work.  We've followed instructions for installation and at first, tierpsy would crash instantly when trying to open a test video to set parameters.  When that didn't work, we tried following instructions in some of the past issue posts.  This got us to be able to set parameters, and we could run the batch processing.  Batch processing would create the folders, but no analysis files ever appear.  The progress bar in the window that opens reaches 100% but the window never closes, so maybe it is not finishing.  
We suspect that there is now some incompatibility of the different versions of anaconda, python, etc with tierpsy.  However, I am not a programmer and can't troubleshoot this very well.  If possible, we would love help!  Perhaps you could update the installation to use only compatible versions?   My apologies for my shortcomings in computer science--I'm mostly a geneticist who would love to be able to use this tool without knowing so much about what's "under the hood."   Thanks very much!!!

**Comment by luigiferiani** [comment]
Hi @ohaganr,

sorry for such a late response but github did not notify me that an issue was opened!

Try following the "install from source" instructions, they are the most up to date and should work (at least on mac, we do know that installation on windows is a bit more involved). I'll be happy to help you further if you have any problem.

**Comment by ohaganr** [comment]
Thanks for your reply, I did finally get Tierpsy tracker working on both mac and pac by the install from source instructions. However, in both cases, the tracker does not finish analysis until I stop the processing and then start it again.  Then, depending on how many videos it has to process, it basically quickly finishes the analysis and puts the analysis files into the appropriate folders.  It seems to me that it had finished the analysis even in the first attempt at processing, but then is waiting for something to finish the process.  Unless I do this, it does not put the analysis files in the folder at all and just keeps “thinking”.  This is actually mostly why I thought it was not working at all—the analysis files don’t show up until stopping and starting the analysis the second time (or even 3rd or 4th if there are lots of videos).  It could be left processing for 24 hours or more but not finish until I stop and start.

Not sure what I have done wrong or if operating system updates have caused problems.  I’m far from a programmer, mostly an “end user.” But I appreciate your development of this excellent tool!

Bob O’Hagan, PhD
Assistant Professor
Biology Department
Montclair State University
***@***.***

**Comment by luigiferiani** [comment]
Hi Bob,

thank you, that's helpful. I appreciate it is a confusing behaviour!

Do you see it happen both on Mac and PC? I've had other users flag a similar behaviour on PC, but never on Mac.

On PC, we've seen it happen especially if the raw videos were already in a local folder. In this case, my suggestion is not to use the temporary folder at all (by unticking it in the Batch Processing GUI): it is most useful when the raw videos are on a remote location, e.g. a network share.

**Comment by ohaganr** [comment]
Yes, for me it was happening on my mac laptop and the pc desktop I use in the lab.  I’ll try unchecking the box!  Thanks again!

Bob O’Hagan, PhD
Assistant Professor
Biology Department
Montclair State University
***@***.***
