### ISSUE TITLE
missing documentation regarding command line use

### ISSUE THREAD

**Issue by cooketho** [Tierpsy/tierpsy-tracker#54]
The documentation says there is an option to use tierpsy tracker on the command line with the following:

```
python cmd_scripts/processMultipleFiles.py -h
```

However, I cannot find this file anywhere. Probably the documentation needs to be updated. Is command line use still supported? If so can you please describe the usage? Thank you!

**Comment by luigiferiani** [comment]
Hi @cooketho,
as you suspected, the documentation needs updating.
If you installed from source, you should be able to just use `tierpsy_process` in the command line (after you activate the conda environment), so for example
``` 
conda activate tierpsy
tierpsy_process --help
```

Let me know if this works for you!
