### ISSUE TITLE
Trouble Creating Skeletons for Single Worm

### ISSUE THREAD

**Issue by nickkel56** [Tierpsy/tierpsy-tracker#70]
Hi,
My name is Nick, I am a researcher working in Dr. Hang Lu's group at Georgia Tech. 

I am trying to process an AVI video of a single worm and it seems the program is unable to create a skeleton for this worm. 
I have looked at the output HDF5 skeletons file and it seems that /plate_worms is populated with data that looks fine where /trajectories_data is empy. The feature HDF5 file is also empty. The worm is being masked perfectly. Your example data also works fine and gives skeletons and features. 

I have played around with some of the parameters with no success, is there any parameters you think could be the issue?
I can send you some of out data via email if you would like.

Thank you,
Nick

**Comment by luigiferiani** [comment]
Hi @nickkel56,

happy to take a look if you send me a link to the files (including the parameters json file) - it does indeed seem to be a parameters issue. 

You can find my email [in the Dockerfile](https://github.com/Tierpsy/tierpsy-tracker/blob/development/docker/Dockerfile#L3).

Cheers,
Luigi

**Comment by wenquan** [comment]
Hi,

We have encountered the same problem when processing our own single worm data.

Is there a general solution for this problem?

Thank you!

Quan

**Comment by luigiferiani** [comment]
Hi,

yes, there is a general solution for this.

Tierpsy has an optional step to apply a CNN-based filter to discard tracked non-worm objects. The NN might not work on all imaging configurations. In general, if Tierpsy seems to have inexplicably not tracked any worm, I'd advise to turn off the NN-based filtering. This can be done by setting, either via the GUI or by editing the parameters json file,
`"nn_filter_to_use": "none"`. 

Disabling the NN-based filtering will not lead to any loss in tracking quality when dealing with single worm videos where the worm is the largest object in the field of view: by selecting the `analysis_type` to be `TIERPSY_SINGLE` Tierpsy will already ignore everything but the largest object.

I'll close this issue now, as setting `nn_filter_to_use` to be `none` fixes this problem, but of course feel free to reopen it if you find it is not the case!

Best regards,
Luigi

**Comment by jskat** [comment]
I had the same issue. The *featuresN output files had nothing in them - for example, the skeletons array had shape (0, 49, 2). Everything worked after I set `"nn_filter_to_use": "none"`.
