### ISSUE TITLE
x and y coordinates

### ISSUE THREAD

**Issue by PradipWEHI** [Tierpsy/tierpsy-tracker#89]
HI 

I am using tierpsy tracker to analyze some videos of worms' movement and their possible location after chemical treatments in a microfluidic maze. I am interested to know that is it possible to know the xy coordinates of the worms using tierpsy tracker. I didn't see the xy coordinates in the output file. If it is possible, please let me know the process to calculate the x y coordinates. 

Thanks

**Comment by xlchu** [comment]
Hi Pradip,

Yeah sure you can. After batch processing your videos, there will be a results folder with a file named metadata_featuresN.hdf5 (or wherever you save the analysed video results). If you read this file (e.g. in python using pd.read_hdf(filepath_metadata_featuresN, '/trajectories_data'), you get a dataframe with the x- and y-coordinates for each worm-id and each frame. Hope this helps.

Best wishes,

Xiao-Liu Chu

**Comment by PradipWEHI** [comment]
Hi, 

Thanks, I above problem is solved. 

I have another question regarding the overall speed (forward, backward and pause) with the time-stamp. I used the "tierpsy_features" as parameters and it's giving the summary of percentile speed in the summary file. To run the "/features_timeseries" option, is it possible to get this information with "tierpsy_features" parameters? Or it is only for "openworm"? 

Thanks

**Comment by PradipWEHI** [comment]
Hi,

Thanks, the above problem is solved.

I have another question regarding getting the overall speed (forward, backward and pause) with the time-stamp data. I used the "tierpsy_features" as parameters and it's giving the summary of percentile speed in the summary file. To run the "/
/features_events/worm_*" option, is it possible to get this information with "tierpsy_features" parameters? Or it is only for "openworm"?

Thanks

**Comment by xlchu** [comment]
Hi Pradip,

Sorry, I'm not sure I understand your question now. Are you referring to the analysis_type when using "set parameters" in tierpsy tracker? If you use "tierpsy" as the analysis_type, then you should be able to extract the not normalised speed from the resulting metadata_featuresN.hdf5 file.

Where in tierpsy tracker is the /features_events/worm_* option? 

I'm sorry, I think I might need some more detailed information to help you.

Best wishes,

Liu

**Comment by WeheliyeHashi** [comment]
No reply from the user
