### ISSUE TITLE
Masking seems good but no skeleton

### ISSUE THREAD

**Issue by lnicole08** [Tierpsy/tierpsy-tracker#90]
Hello, I've installed the Tierpsy tracker via Docker and its been working great! However, Im having issues with the skeletons. During set parameters, im able to see the mask of the worm well and also tweaked additional parameters to try to identify the worm better. However, no matter what i do, the tracker does not show me a single skeleton or shows me inaccurate skeletons. This might be because of the low res video quality (Sample below) Please kindly advise on which parameters I can change to help identify the worms better!

![image](https://user-images.githubusercontent.com/83282224/214782951-93e9db0d-6f1b-4307-8b98-cce977ffb652.png)

Thank you !

**Comment by aexbrown** [comment]
I think the issue isn't the resolution but the contrast.  It's just hard for the algorithm to identify a continuous worm.  The skeletons are drawn by first tracing the outline and then drawing the midline between the two sides.  In the example here there's a bit of a gap that causes it to only get half the worm.  Unfortunately I don't think you'll be able to solve that with different parameters but will need videos with higher contrast and/or more continuous worms.  

We're working on an improved skeletonisation algorithm that should help (following additional training on your type of data) but it's not ready to release just yet.
